print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print("minimized number of print function")
print("    *\n   * *\n  *   *\n *     *\n***   *** ")
print("  *   *\n  *   *\n  *****")
print("arrow twice as large")
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("******     ******")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *******")
print('Duplicte the string')
print("    *     " *2)
print("   * *    " *2)
print("  *   *   " *2)
print(" *     *  " *2)
print("***   *** " *2)
print("  *   *   " *2)
print("  *   *   " *2)
print("  *****   " *2)

y = input("Enter flower name: " )

if y == "Spathiphyllum" :
    print("Yes - Spathiphyllum is the best plant ever!")
elif y == "spathiphyllum" :
        print("No, I want a big Spathiphyllum!")
else:
    print("Spathiphyllum! Not", y + "!")
